spring:
  application:
    name: aurum-core-banking

  datasource:
    url: jdbc:h2:mem:banking_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_schema: public

  h2:
    console:
      enabled: true

  flyway:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8180/realms/banking/protocol/openid-connect/certs}
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/banking}

encryption:
  secret-key: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

rate-limit:
  transfer:
    capacity: 10
    refill-tokens: 10
    refill-seconds: 60

logging:
  level:
    com.aurum.corebanking: INFO
    org.drools: WARN
    org.springframework.security: WARN