global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'aurum-banking'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']
    # In production the actuator runs on port 8081 (application-prod.yml):
    # - targets: ['localhost:8081']

  - job_name: 'keycloak'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8180']
